project_id = "czpqutbtcfdnffqaespx"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false

  [functions.preview-transactional-email]
    verify_jwt = false

  [functions.send-contact-email]
    verify_jwt = false
