/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyMindorionRouteImport } from './routes/why-mindorion'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProposaliqRouteImport } from './routes/products.proposaliq'
import { Route as ProductsGrowthiqRouteImport } from './routes/products.growthiq'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiPublicGeoRouteImport } from './routes/api/public/geo'

const WhyMindorionRoute = WhyMindorionRouteImport.update({
  id: '/why-mindorion',
  path: '/why-mindorion',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProposaliqRoute = ProductsProposaliqRouteImport.update({
  id: '/products/proposaliq',
  path: '/products/proposaliq',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsGrowthiqRoute = ProductsGrowthiqRouteImport.update({
  id: '/products/growthiq',
  path: '/products/growthiq',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiPublicGeoRoute = ApiPublicGeoRouteImport.update({
  id: '/api/public/geo',
  path: '/api/public/geo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/use-cases': typeof UseCasesRoute
  '/why-mindorion': typeof WhyMindorionRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/products/growthiq': typeof ProductsGrowthiqRoute
  '/products/proposaliq': typeof ProductsProposaliqRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/use-cases': typeof UseCasesRoute
  '/why-mindorion': typeof WhyMindorionRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/products/growthiq': typeof ProductsGrowthiqRoute
  '/products/proposaliq': typeof ProductsProposaliqRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/use-cases': typeof UseCasesRoute
  '/why-mindorion': typeof WhyMindorionRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/products/growthiq': typeof ProductsGrowthiqRoute
  '/products/proposaliq': typeof ProductsProposaliqRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contact'
    | '/pricing'
    | '/security'
    | '/use-cases'
    | '/why-mindorion'
    | '/blog/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/products/growthiq'
    | '/products/proposaliq'
    | '/api/public/geo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contact'
    | '/pricing'
    | '/security'
    | '/use-cases'
    | '/why-mindorion'
    | '/blog/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/products/growthiq'
    | '/products/proposaliq'
    | '/api/public/geo'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contact'
    | '/pricing'
    | '/security'
    | '/use-cases'
    | '/why-mindorion'
    | '/blog/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/products/growthiq'
    | '/products/proposaliq'
    | '/api/public/geo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  SecurityRoute: typeof SecurityRoute
  UseCasesRoute: typeof UseCasesRoute
  WhyMindorionRoute: typeof WhyMindorionRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ProductsGrowthiqRoute: typeof ProductsGrowthiqRoute
  ProductsProposaliqRoute: typeof ProductsProposaliqRoute
  ApiPublicGeoRoute: typeof ApiPublicGeoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-mindorion': {
      id: '/why-mindorion'
      path: '/why-mindorion'
      fullPath: '/why-mindorion'
      preLoaderRoute: typeof WhyMindorionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/proposaliq': {
      id: '/products/proposaliq'
      path: '/products/proposaliq'
      fullPath: '/products/proposaliq'
      preLoaderRoute: typeof ProductsProposaliqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/growthiq': {
      id: '/products/growthiq'
      path: '/products/growthiq'
      fullPath: '/products/growthiq'
      preLoaderRoute: typeof ProductsGrowthiqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/public/geo': {
      id: '/api/public/geo'
      path: '/api/public/geo'
      fullPath: '/api/public/geo'
      preLoaderRoute: typeof ApiPublicGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  SecurityRoute: SecurityRoute,
  UseCasesRoute: UseCasesRoute,
  WhyMindorionRoute: WhyMindorionRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ProductsGrowthiqRoute: ProductsGrowthiqRoute,
  ProductsProposaliqRoute: ProductsProposaliqRoute,
  ApiPublicGeoRoute: ApiPublicGeoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
